### PR TITLE
Navbar text overflow

### PR DESCRIPTION
**Pull request by vinayaksh42**
Fixes: #524

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Tested on Firefox and chrome for iOS. It's a tACK for me. 

image
image

**Review by benalleng — APPROVED** [review]
LGTM!

**Comment by benalleng** [comment]
Looks like we were a bit too hasty, this still seems to be an issue with that challenges themselves, and I am having trouble getting it to work locally.

**Comment by vinayaksh42** [comment]
> Looks like we were a bit too hasty, this still seems to be an issue with that challenges themselves, and I am having trouble getting it to work locally.

Can you share screenshot of it as well as tell about the scenario in which it is not working.

**Comment by benalleng** [comment]
Challenges don't seem to be working and locally it doesn't work at all
### on dev.savingsatoshi
image

### locally
image

**Comment by benalleng** [comment]
Some of the problem might have to do with the complexity of how the Chapter#, Challenge# is rendered

**Comment by vinayaksh42** [comment]
> Challenges don't seem to be working and locally it doesn't work at all
> 
> ### on dev.savingsatoshi
> image
> 
> ### locally
> image

Try running these commands 
```
git fetch upstream dev
git rebase upstream/dev
```

Your local branch is most probably not in sync with the dev branch as the changes are working perfectly for me locally as well as in production.

The issue with challenges-navbar in mobile view is more related to how we handle it from a design perspective. The aim of this PR was not to fix it as it was not mentioned in the scope of the issue #524 

Thanks for reporting it @benalleng, @GBKS do you have any suggestions on how we can handle the overflowing text in challenges-navbar?

**Comment by ecurrencyhodler** [comment]
Yea I'll create a separate issue. The navbar for challenges will require design to give feedback on it.

**Pull request merged**
