### PR TITLE
Removed /en ending from Homepage

### LINKED ISSUE #189: Remove /en ending for website
**Describe the enhancement**
We should remove the /en in our url: https://savingsatoshi.com/en

**Additional information**
We don't currently support another language at this time.

### PR DESCRIPTION
**Pull request by vinayaksh42**
Fixes #189 

Changes:
- Moved `page.tsx`, `head.tsx`, and `layout.tsx` to `app` folder (https://github.com/saving-satoshi/saving-satoshi/issues/189#issuecomment-1444557258)
- Added `page.tsx` to `app/[lang]` folder which imports the `app/page.tsx` component.
- Added condition in `middleware.ts` to not Redirect if the requested page ends with `'/'` and the locale is `en`.
- The default locale is set to `en` if `lang` prop in `lib/translate.tsx` is not provided.  (https://github.com/saving-satoshi/saving-satoshi/issues/189#issuecomment-1444166916)

I tried to implement a solution that will allow us to remove `en` If the locale is set to English but could not find a reliable solution. Either we can move all the folder inside `app/[lang]` to `app` while also having a copy of all the folders inside `app/[lang]` as well and ignore Redirect for `en` locale but will double our work whenever we want to add a new page to `app`.

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Tested that the url doesn't end with /en.

**Review by afterburn — CHANGES_REQUESTED** [review]
Thanks @vinayaksh42, works perfectly when I set my locale to English, but when I set it to Dutch, click on the "Start the demo" button on the homepage, it navigates me to `/chapters` (so without the `/en`) which then doesn't load.

We don't have to support `/nl` but when users have another locale set as their default, navigation to other pages should still work. Do you think you can fix that?

**Comment by ecurrencyhodler** [comment]
When I tested it auto-navigated me to a url that ends with /en. Is that because my locale is set to english?

**Comment by afterburn** [comment]
> When I tested it auto-navigated me to a url that ends with /en. Is that because my locale is set to english?

Probably, in Chrome the settings look like this:

image

Your default locale is the one you put on top.

**Comment by benalleng** [comment]
> it navigates me to `/chapters` (so without the `/en`) which then doesn't load.

I encountered this behavior when exploring this issue as well. I believe that the website is treating `chapters` as a new locale so it is attempting to load the homepage and trying to load the language as `chapters`. the same happens with `about`

**Comment by afterburn** [comment]
@vinayaksh42 thanks for the update, using a `Dutch` locale I am now correctly navigated to `/nl/chapters`, and the translations [seem to work](https://saving-satoshi-git-fork-vinayaksh42-issue189-saving-satoshi.vercel.app/nl/chapters). However, for `/en` some translations are now [missing for me](https://saving-satoshi-git-fork-vinayaksh42-issue189-saving-satoshi.vercel.app/en/chapters):

image

**Comment by afterburn** [comment]
Okay issue seems to be resolved for me, can anyone else verify to make sure?

**Comment by vinayaksh42** [comment]
no the homepage - https://saving-satoshi-4sif06ond-saving-satoshi.vercel.app/ displays this now:
Screenshot 2023-03-09 at 2 37 04 AM

The chapter description seems to be loading correctly now.

**Comment by afterburn** [comment]
> the homepage - https://saving-satoshi-4sif06ond-saving-satoshi.vercel.app/ displays this now: Screenshot 2023-03-09 at 2 37 04 AM
> 
> The chapter description seems to be loading correctly now.

Yeah I just edited my previous comment, its fine, I'll fix it after we merge this one.

**Comment by vinayaksh42** [comment]
> Yeah I just edited my previous comment, its because with an english locale there is no `/en` on the homepage so the `params.lang` is undefined. Its fine, I'll fix it after we merge this one. You can see for dutch it works because then it we redirect you to [this link](https://saving-satoshi-git-fork-vinayaksh42-issue189-saving-satoshi.vercel.app/nl).

Yes, it is working for https://saving-satoshi-4sif06ond-saving-satoshi.vercel.app/en and https://saving-satoshi-4sif06ond-saving-satoshi.vercel.app/nl

**Review by afterburn — APPROVED** [review]

**Comment by afterburn** [comment]
Create [this issue](https://github.com/saving-satoshi/saving-satoshi/issues/249) for it. Will work on this now. Thanks @vinayaksh42 and @benalleng.

**Pull request merged**
