### PR TITLE
Fix: max- width instead of width and fade in and out on waiting text and images

### PR DESCRIPTION
**Pull request by 0tuedon**
This Pr references #587  and solves  on the styling  of chapter 3 challenge 2.

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Thanks for submitting this pr. Let's put a pause on this until @GBKS can clarify on a couple issues. This isn't a blocker for launch.

I can confirm the waiting fades in and out which is nice. I'm not sure how the centered text should look though.

**Comment by GBKS** [comment]
Thanks for working on this. I still see some layout issues and left-aligned text. Screenshots are via the Responsive design mode on Safari on Desktop.

image

image

Generally, it is not a good idea to use fixed width or height for content containers (especially height). Text will render at different lengths across translations, people change text size, etc.

**Comment by 0tuedon** [comment]
> Thanks for working on this. I still see some layout issues and left-aligned text. Screenshots are via the Responsive design mode on Safari on Desktop.
> 
> image image
> Generally, it is not a good idea to use fixed width or height for content containers (especially height). Text will render at different lengths across translations, people change text size, etc.

hey @GBKS  before i commit my changes i do what to know if this  loading style works

https://github.com/saving-satoshi/saving-satoshi/assets/90271995/90704101-840d-411a-aea6-380566542467

**Comment by 0tuedon** [comment]
@GBKS  can i get your feedback on the new fix

**Comment by GBKS** [comment]
Thanks for the tweaks. I still see layout issues on mobile.

image

Before any of the other 3 miners are loaded, the grid nicely fits into the screen. As soon as one of them is loaded, it expands to the screen edges (it should keep the first state with the padding). This is likely due to the boxes responding to the width of the labels. The layout logic should be reverse where the box defines the width, and the label resizes its width accordingly.

Again, it is not a good idea to use fixed heights. Using a min-height is a better idea, because it allows the container to resize if the content happens to be longer (localization to another language, for example, might cause this).

**Comment by 0tuedon** [comment]
> Thanks for the tweaks. I still see layout issues on mobile.
> 
> image
> 
> Before any of the other 3 miners are loaded, the grid nicely fits into the screen. As soon as one of them is loaded, it expands to the screen edges (it should keep the first state with the padding). This is likely due to the boxes responding to the width of the labels. The layout logic should be reverse where the box defines the width, and the label resizes its width accordingly.
> 
> Again, it is not a good idea to use fixed heights. Using a min-height is a better idea, because it allows the container to resize if the content happens to be longer (localization to another language, for example, might cause this).

Alright, i have been able to restraint from using fixed width, and i have been able to fix the layout issues mentioned, you could review

**Review by GBKS — APPROVED** [review]
Looking good, thank you for addressing my feedback.

**Pull request merged**
