### PR TITLE
Remove "chapters" string from keysMeta

### LINKED ISSUE #478: Remove chapters string from keysMeta urls
Currently the keysMeta uses the full url but throughout the codebase we split up the url into routes.chapters + lessonKey

Reason for change: if in the future we decide to place keys outside of the standard ch1-10 story with sidequests or other utility functions e.g. a general purpose transaction parsing tool like https://siminchen.github.io/bitcoinIDE/build/editor.html I think this Might live outside of the standard `c/hapters/chapterSlug/lessonKey` route additionally this simply keeps consistency with the rest of our current codebase involving urls

### PR DESCRIPTION
**Pull request by shaavan**
Resolves #478

- Use routes.chaptersURL to maintain consistency in the manner of using links in the codebase.

Relevant discussion [link](https://github.com/saving-satoshi/saving-satoshi/pull/477#discussion_r1206903414)

### CODE REVIEW

**Comment by sabakhilji** [comment]
I noticed after finishing a challenge, every time while moving on to the next challenge screen flickers. Also, there is no flicker while moving backward.

**Comment by ecurrencyhodler** [comment]
@sabakhilji do you have a screen recording you could share?

**Comment by shaavan** [comment]
> @sabakhilji do you have a screen recording you could share?

Yes, the recording will be of good help. It would help narrow down the cause of the problem.
Also, please check whether the problem is present in the master branch or not. Thanks!

**Comment by sabakhilji** [comment]
> > @sabakhilji do you have a screen recording you could share?
> 
> Yes, the recording will be of good help. It would help narrow down the cause of the problem. Also, please check whether the problem is present in the master branch or not. Thanks!

No, I don't have, but I will record it now.

**Comment by sabakhilji** [comment]
The problem comes in challenge 2 here is the recording:

https://github.com/saving-satoshi/saving-satoshi/assets/52318459/602de2bc-7f4d-4897-967c-81c4eda511f7

**Comment by shaavan** [comment]
Updated from e713c33085bbb2572254ac4a73bc67741ed6bb09 to 881e70d9eff633f322f7d8b5c952a9d7f2c9a7a3 ([pr4795.01](https://github.com/shaavan/saving-satoshi/commits/pr495.01) -> [pr495.02](https://github.com/shaavan/saving-satoshi/commits/pr495.02), [diff](https://github.com/shaavan/saving-satoshi/compare/pr495.01..pr495.02))
Addressed @sabakhilji comment

Updates:
1. Rebased over the master
2. Use a `const` variable to create a route before passing through `router.push()`.

@sabakhilji 
I have made changes to address the flickering issue. Please have another look, and let me know if the flickering continues.
Thanks!

**Comment by sabakhilji** [comment]
> Updated from [e713c33](https://github.com/saving-satoshi/saving-satoshi/commit/e713c33085bbb2572254ac4a73bc67741ed6bb09) to [881e70d](https://github.com/saving-satoshi/saving-satoshi/commit/881e70d9eff633f322f7d8b5c952a9d7f2c9a7a3) ([pr4795.01](https://github.com/shaavan/saving-satoshi/commits/pr495.01) -> [pr495.02](https://github.com/shaavan/saving-satoshi/commits/pr495.02), [diff](https://github.com/shaavan/saving-satoshi/compare/pr495.01..pr495.02)) Addressed @sabakhilji comment
> 
> Updates:
> 
>     1. Rebased over the master
> 
>     2. Use a `const` variable to create a route before passing through `router.push()`.
> 
> 
> @sabakhilji I have made changes to address the flickering issue. Please have another look, and let me know if the flickering continues. Thanks!

Hey, I checked it, still facing the issue. Additionally, I got this which is problematic I guess:
Screenshot (107)
 
I got stuck at ch2 mining1

**Comment by shaavan** [comment]
@sabakhilji

I wrote [this](https://github.com/saving-satoshi/saving-satoshi/pull/495#issuecomment-1584693154) comment but forgot to push the changes. Well, that's what happens when you prepare the update comment before updating 😅 

> I got stuck at ch2 mining1

Thanks for bringing it to my notice. I tried the production build, but I couldn't see this issue.
Try the challenge once in incognito mode to see if the issue persists!
Thanks!

**Comment by vinayaksh42** [comment]
> I also checked the latest production version , found same problem there
> Screenshot (108)

@ecurrencyhodler is this bug similar to the one we talked about earlier?
I think this bug might be unrelated to this PR.

@sabakhilji did you exit the tab while running the ch2.Mining challenge? or anything else you did while attempting the mining challenge. @ecurrencyhodler reported this issue earlier but we were unable to reproduce it reliably.

**Comment by ecurrencyhodler** [comment]
tACK!

**Pull request merged**
