### PR TITLE
Success animation

### PR DESCRIPTION
**Pull request by benalleng**
Just a test PR to demonstrate Lottie animations and practice using it a little.
animation used, [lottiefile](https://lottiefiles.com/79952-successful)

Answer: 

04ffff001d0104455468652054696d65732030332f4a616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f66207365636f6e64206261696c6f757420666f722062616e6b73

[Preview (not working)](https://saving-satoshi-git-fork-benalleng-animations-savingsatoshi.vercel.app/en/chapters/chapter-1/genesis-2)
[Preview (working)](https://saving-satoshi-jkej9lygp-saving-satoshi.vercel.app/en/chapters/chapter-1/genesis-2)

### CODE REVIEW

**Comment by benalleng** [comment]
Seems like its not completely loading.

**Comment by sabakhilji** [comment]
> Any ideas on why this isn't loading as expected?

Seems like this is a common issue in Lottie. I am not sure,but the answer might be this:
https://github.com/airbnb/lottie-web/issues/2656
Look at the last post.

**Comment by afterburn** [comment]
Looks great!

**Comment by benalleng** [comment]
Closing for cleanliness

**Pull request closed without merging**
