### PR TITLE
formatHash returns rows properly

### LINKED ISSUE #489: Ch.2 Challenge 3 - Put small hashes in a row, not column
The small hash is displayed in columns - should be rows. See image below.
239549946-e8800aa3-f306-46e5-a9ca-2481420b5d4b

This will require changes to the lib/formatHash.tsxfile which is being used in other challenges as well so we might have to add an extra prop for changing the order in which the hashes are displayed.

### PR DESCRIPTION
**Pull request by benalleng**
Closes #489

### CODE REVIEW

**Comment by afterburn** [comment]
Hey @vinayaksh42, I retargeted your branch to `dev`, please resolve conflicts when you have time, thanks

**Comment by ecurrencyhodler** [comment]
Looks good!

But the hash section looks off at the bottom. @GBKS on this to see if this needs be to updated by design. 

image

**Comment by GBKS** [comment]
Yes, the hash can naturally wrap. No need here on mobile to have specific break points. I wish CSS had something like a breakpoint-hint that is only applied under certain conditions.

**Comment by benalleng** [comment]
New word-break changes on mobile
image

**Comment by ecurrencyhodler** [comment]
tack for me. 

image

**Review by vinayaksh42 — APPROVED** [review]

**Pull request merged**
