### PR TITLE
Cleanup: TS fixes, package bumps and  icons fixes

### PR DESCRIPTION
**Pull request by afterburn**
This PR:
- Bumps next.js to the latest version
- Removes unnecessary packages
- Refactors the way we load icons
- Fixes all TypeScript errors

### CODE REVIEW

**Comment by afterburn** [comment]
@ecurrencyhodler @benalleng please only test for regression compared to the `master` branch

**Comment by ecurrencyhodler** [comment]
Mostly a tack. But I did see this extra white space button on the outro that shouldn't be there.
Screenshot 2023-04-24 at 11 39 12 AM

**Comment by benalleng** [comment]
while that button exists only in this branch, it will not be a problem for long, it only exists because we currently don't want users to go straight to chapter 2 as it is not yet finished, its a pseudo continue button at the moment

**Comment by benalleng** [comment]
Also a tACK from me, all the icons load as expected!

**Review by ecurrencyhodler — APPROVED** [review]

**Pull request merged**
