### PR TITLE
Fix copy in Navbar

### LINKED ISSUE #172: Update dynamic copy in the nav bar
The top line should indicate the current chapter and challenge (but NOT show the name of the chapter or challenge as it does now). The bottom line should show "Intro" when on a chapter intro page, and otherwise the name of the challenge/page. We can set this to always show the name of the challenge/page if that's easer (and not have an "intro" fallback).

image

Screenshot of the live site:

image

### PR DESCRIPTION
**Pull request by afterburn**
## Summary
This PR should close #172.

## Checklist
- [x] Build was run locally and any changes were pushed
- [x] Ensure that the title clearly describes the changes
- [x] Issue to be referenced in the PR description rather than in the commits or PR title
- [x] Clean commit history

### CODE REVIEW

**Comment by GBKS** [comment]
Tested and looks great. One small tweak is to change the '-' between chapter and challenge numbers to a ','.

**Review by shaavan — COMMENTED** [review]
The changes look good, and I verified that it renders the correct behavior for the **Address.tsx**, as explained in #172.

I have two suggestions for this PR.

1. Replacing the `-` span with a comma `,` (which @GBKS already pointed out).
2. Squashing the commits to keep the commit history clean.

**Comment by afterburn** [comment]
Thanks guys, I changed ` - ` to `, `. We can squash commits via the Github interface (instead of Merge pull request, open the dropdown and select Squash and merge), no need to force push anything.

**Review by GBKS — APPROVED** [review]
ACK. Looks great. Thank you.

**Pull request merged**
