### PR TITLE
Match images to Figma

### PR DESCRIPTION
**Pull request by GBKS**
Various images were outdated, not crisp, or not the necessary minimum size for desktop retina screens. So I reviewed them and re-exported as needed. The [chapters overview page](https://saving-satoshi-git-feature-image-updates-savingsatoshi.vercel.app/en/chapters) should look very different now.

👊[Check the preview](https://saving-satoshi-git-feature-image-updates-savingsatoshi.vercel.app/en/chapters)✊🏼

### CODE REVIEW

**Comment by adamjonas** [comment]
There are significant size savings by running these through imageoptim which just removes the metadata. Probably worth doing if we are going to switch these out.

Screenshot 2023-10-02 at 9 53 02 AM

**Comment by GBKS** [comment]
If you are concerned about browser load performance, the framework already optimizes the images (size and compression).

**Comment by adamjonas** [comment]
Yes, that was my main concern so not a necessary change, but generally I prefer to load images that have been run through imageoptim or the like so file sizes are only what we need.

**Comment by adamjonas** [comment]
ACK on overview page and first couple of chapters

**Comment by GBKS** [comment]
The images are now compressed.

**Review by benalleng — APPROVED** [review]
LGTM! Ran through the site and all the images look to match their figma counterparts

**Review by afterburn — APPROVED** [review]

**Comment by afterburn** [comment]
We're also using [Next Images](https://nextjs.org/docs/pages/building-your-application/optimizing/images) which should optimize automatically for us

**Pull request merged**
