### PR TITLE
Add success page(issue # 261)

### PR DESCRIPTION
**Pull request by sabakhilji**
adding a success page after the first task.

## Pull Request checklist

Please review the below PR requirements:

- Build was run locally and any changes were pushed
- Ensure that the title clearly describes the changes
- Issue to be referenced in the PR description rather than in the commits or PR title
- Clean commit history

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Addresses https://github.com/saving-satoshi/saving-satoshi/issues/261

**Comment by benalleng** [comment]
@ecurrencyhodler I think you need to say closes #261 it has to be one of the words listed [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to auto-link

**Comment by sabakhilji** [comment]
> Addresses #261

Yes, this PR addresses issue 261 and this PR will not close the issue still working on it .
Thanks @benalleng and @ecurrencyhodler

**Comment by sabakhilji** [comment]
Also, I have a question @benalleng where should I place the success page?
Do I need to make a separate folder for it or should I place it directly in the lessons folder?

**Comment by sabakhilji** [comment]
One more question how can I can upload the image to the repo?

**Comment by benalleng** [comment]
So i think for now, the success page should go with the other genesis challenges. As far as how to add a new image, you should be able to place it in the `/public/assets/images` folder and reference it from there

**Pull request closed without merging**
