### PR TITLE
Tooltip improvements & copy change

### LINKED ISSUE #179: Add support for a tags in tooltips & modify copy
The tool tip text should briefly explain what a block explorer is, and link out to a definition of the term (instead of a block explorer directly). The external link should open in a new window. This is on the [chapter 1, challenge 1 page](https://savingsatoshi.com/en/chapters/chapter-1/genesis-1).

image

### PR DESCRIPTION
**Pull request by afterburn**
## Summary
This PR closes #179 and #220, it adds support for adding `<a>` tags to tooltips and prevents the tooltip from being deactivated when you move your cursor to the tooltip itself.

- I couldn't find a good neutral page that explains what a block explorer is so I left the original url to blockstream in place. Feel free to modify this in a separate PR if you have a better alternative.

- @GBKS, @satsie or @ecurrencyhodler please confirm whether the copy for the tooltip is okay, feel free to suggest better alternatives.

saving-satoshi-tooltips-2

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Let's try this copy and url:

"A [block explorer](https://bitcoinops.org/en/topics/block-explorers/) is a useful tool to quickly look up information about bitcoin transactions."

Also does your code also resolve this issue mobile tooltips? https://github.com/saving-satoshi/saving-satoshi/issues/220

**Comment by afterburn** [comment]
> A [block explorer](https://bitcoinops.org/en/topics/block-explorers/) is a useful tool to quickly look up information about bitcoin transactions.

Made the requested change. No it does not fix #220, I can address that issue in a separate PR.

**Comment by afterburn** [comment]
Noticed an issue with the tabs in the Topbar, converting this to a draft until issue has been resolved.

**Comment by afterburn** [comment]
Should be ready to review now

**Comment by ecurrencyhodler** [comment]
Tested. Sizing of the expanded tooltip looks great. 

I think the pr does address #220. I am now able to click on the tooltip for mobile. Then when I tap on "block explorer" in the tip it takes me to the website.  image

**Comment by afterburn** [comment]
> Tested. Sizing of the expanded tooltip looks great.
> 
> I think the pr does address #220. I am now able to click on the tooltip for mobile. Then when I tap on "block explorer" in the tip it takes me to the website.

Oh great, then I think I may have fixed the issue by accident 😆

**Comment by ecurrencyhodler** [comment]
LOLL our boy kevin here is so efficient he does it by accident!

Okay let's get one code review and then we can merge.

**Comment by GBKS** [comment]
Sweet, that looks great.

A small addition would be to find a solution for accessibility. Requires a bit of mark-up and potentially that the tool tip is always visible in the HTML (not 100% on that one). Some more info [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role).

**Comment by afterburn** [comment]
> Sweet, that looks great.
> 
> A small addition would be to find a solution for accessibility. Requires a bit of mark-up and potentially that the tool tip is always visible in the HTML (not 100% on that one). Some more info [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role).

Thanks @GBKS, what markup would be required to make this more accessible?
This is what our tooltip currently looks like:

```html
<span class="tooltip absolute top-0 left-0 z-10 max-w-md border border-white bg-back px-5 py-2 text-center shadow-lg shadow-black/25 transition-opacity delay-150 ease-in-out pointer-events-none opacity-0">
  <span class="absolute left-1/2 h-3 w-3 border-l border-t border-white bg-back bottom-0" style="transform: translate3d(-50%, 50%, 0px) rotate(225deg);"></span>
  <span class="font-nunitoleading-none text-white">A <a href="https://bitcoinops.org/en/topics/block-explorers/" target="_blank" rel="noreferrer" class="underline">block explorer</a> is a useful tool to quickly look up information about bitcoin transactions.</span>
</span>
```

This markup is always visible in the html btw, so that should cover the second part of your remark. 😁

**Review by satsie — APPROVED** [review]
ACK f03ddd33011bcca52e342ca7654430ad704763c2

Seems fine to do a follow up PR for the accessibility improvements after the demo (or before, if there is time)

**Pull request merged**
