### PR TITLE
Finalize scripting challenge

### LINKED ISSUE #332: Improve Python interactivity
We're currently using [Pyodide](https://pyodide.org/en/stable/) to run Python in the browser, the pyodide process is running in a separate [webworker](https://pyodide.org/en/stable/usage/webworker.html).

One of the limitations that I've run into with pyodide is that the full python script needs to finish running before it sends over the data back to javascript (which we then use to render the output). This is not optimal because we want to achieve a rich experience as is shown on [Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2873-28038&t=w9qcMv6uKNrv1ClZ-4).

This issue is about:
1. Finding out if its possible to periodically send data back to JavaScript.
2. If it is not, finding an alternative solution to replace pyodide with. One idea that comes to mind is transpiling Python code to Javascript code before execution.

Constraints:
- We should not spend too much time on this as the client-side approach is theorized to be a temporary solution. If we have a server-side Python repl this will no longer be an issue.

### LINKED ISSUE #392: Complete Ch.2 L2: Scripting
The remaining items for this feature are:
1. Write the script
2. Timeout on running the script
3. ~~Make it match [figma.](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2873%3A27799&t=toS1MMRMWjlha2XE-1)~~ Will be addressed in a separate issue #400

### PR DESCRIPTION
**Pull request by afterburn**
Closes #332 and #392.

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Not sure if the script is supposed to be auto-populated for this version but it isn't right now.
Screenshot 2023-04-21 at 8 43 56 AM

And after I input the script, nothing happens.
Screenshot 2023-04-21 at 8 43 49 AM

**Comment by ecurrencyhodler** [comment]
tACK! Thanks for the tips. Am I a python dev now? 😂 jm

https://user-images.githubusercontent.com/32662508/233686294-a63c3e77-7036-408d-b9f5-187aad68d818.mov

**Comment by afterburn** [comment]
@ecurrencyhodler thanks for the tACK but this PR is still in draft hehe, I will also resolve #400 in this one.

**Comment by afterburn** [comment]
Actually I will address #400 in a separate PR, @GBKS is investigating a proper solution first.

**Comment by ecurrencyhodler** [comment]
Not sure if my code is bad but I got this error.
Screenshot 2023-04-22 at 8 30 47 AM

"Running
find_hash(nonce)
Result
No output
Evaluation
Traceback (most recent call last): File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = coro.send(None) File "/lib/python3.10/_pyodide/_base.py", line 532, in eval_code_async await CodeRunner( File "/lib/python3.10/_pyodide/_base.py", line 355, in run_async coroutine = eval(self.code, globals, locals) File "<exec>", line 112, in <module> File "<exec>", line 88, in run File "<exec>", line 75, in find_hash AttributeError: 'sha256' object has no attribute 'hexhdigest'"

**Comment by afterburn** [comment]
@ecurrencyhodler yeah like the error tells you on the last line 'hexhdigest' doesnt exist, should be 'hexdigest'

**Comment by afterburn** [comment]
@ecurrencyhodler I can spend some time on improving error logging in a separate pr

**Comment by ecurrencyhodler** [comment]
It worked!

Should the green text disappear when someone enters a value into the terminal? Would like @GBKS and @benalleng thoughts on this too.

Screenshot 2023-04-22 at 8 30 47 AM

**Comment by afterburn** [comment]
@ecurrencyhodler thats just a code comment, users can choose to remove it themselves IMO. Its pretty common to have code comments containing pseudocode or just a general explanation on what kind of code the user should write.

**Comment by ecurrencyhodler** [comment]
Okay tool tips doesn't seem to be working.
Screenshot 2023-04-23 at 9 02 56 AM

**Comment by benalleng** [comment]
Tooltips are a key error genesis_two vs chapter_one.genesis_two. I fixed this in #333

**Comment by ecurrencyhodler** [comment]
Okay then it's a tACK for me. I ran through ch.1, clicked various buttons/links, and design/fonts all seem to check out.

**Review by benalleng — APPROVED** [review]
tACK and the code looks good 👍

**Pull request merged**
