### PR TITLE
Chapter 3: Fix mining reward amount

### PR DESCRIPTION
**Pull request by satsie**
This PR addresses issue https://github.com/saving-satoshi/saving-satoshi/issues/1111. I was happily surprised that fixing it only required a few small changes.

### CODE REVIEW

**Review by Emmanuel-Develops — COMMENTED** [review]
hello @satsie, it seems the share was calculated based off `blocks found` rather than `partial solutions` which explains the discrepancies you found.

percentage-block-found


### block found percentage
i.e using (block found percentage) we have it currently as shown in the image above
- user (You): 26.32% of 6.1 -> 1.61
- Mining Maniacs: 15.79% of 6.1 -> 0.96
...
_adding up all the shares give 6.1_

### partial solutions
Following partial solutions instead as you correctly pointed out:
For the user (You) to have `1.61` from a share split where they contributed `21.74%`, the total value to be shared should be `7.4057..` instead of `7.36`.

This however introduces another problem as the value for other miners in the pool have to be recalculated.
i.e we should have
- user (You): 21.74% of `7.4057..` -> 1.61
- Mining Maniacs: 20.05% of `7.4057..` =~ `1.48..`
...

I'm uncertain on what amount of rounding or decimals to use which is why there is `..` at the end

**Comment by satsie** [comment]
ooooo @Emmanuel-Develops you are right! The total reward should be 7.41 BTC (rounded to 2 decimal places). I don't know what I was thinking when I initially changed it to 7.36. I must have been half asleep :laughing: 

I updated the rewards for the other miners to now be calculated using the partial shares (and not blocks found). They are as follows:
- you: 1.61 btc
- Mining Maniacs: 1.49 btc
- Coin Crunchers: 1.41 btc
- Hash Hoppers: 2.9 btc

Also attaching a screencap with the new numbers (btw the screencap you added to your comment is private and I wasn't able to view it):
Screenshot from 2024-10-09 23-31-56

I added up all the individual rewards and as expected, the sum is 7.41. Can you double check my work in this PR? Thank you!

**Comment by Emmanuel-Develops** [comment]
> (btw the screencap you included in your comment is private and I wasn't able to view it):

oops, updated it.

> I added up all the individual rewards and as expected, the sum is 7.41. Can you double check my work in this PR? Thank you!

Nice!
I've looked through it and it all checks out

**Review by Emmanuel-Develops — APPROVED** [review]

**Comment by satsie** [comment]
Amazing!! Tysm!

**Pull request merged**
