### PR TITLE
Made challenge links on the chapters page clickable

### PR DESCRIPTION
**Pull request by GBKS**
This is part of issue #10. The Challenges component previously only received and showed a list of lesson IDs. With these changes it finds the respective challenge data to show the title and a link to the respective challenge content.

Note that the links don't work right now. Contentlayer is not producing the correct links we need. This can be handled in a separate PR. Maybe a good task for Juan.

## Pull Request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build was run locally and any changes were pushed
- [ ] Lint has passed locally and any fixes were made for failures

## Pull Request type

Please check the type of change your PR introduces:

- [ ] :bug: Bugfix
- [x] :sparkles: Feature
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :wrench: Other (please describe):

-

resolved #

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by GBKS** [comment]
@ggwilin this PR still doesn't build. Could you please give me access to Vercel so I can see what the problem is and address it?

**Comment by GBKS** [comment]
OK, I was able to debug the issue via `npm run build`. An import was missing, and a prop was misspelled.

**Comment by GBKS** [comment]
@ggwilin I figured it out how to construct the links. I'd appreciate your review now. I also packed in a handful of minor fixes that the console complained about related to improperly formatted style attributes.

**Comment by aureleoules** [comment]
Changes look good to me. I tested that the links on the chapter page are now clickable.

I suggest squashing 604b3f034ed0420ade08cba03e77e0bc87e3e768, fc9bf692047ae0e0049090d3bc06d5c081f100aa, 54f6e647647593b133c54c671ef8a18e08653d7e and 247099b4625fc956a0b23e53df6e6e1e58b5d3a2 together though.
And squash b5bf1f31d4c5f3af6b393003674414273d69e102 081227bb77f080c153f337747ee6bec9973473c7 39a0a718fd5d75751be1aa89a03e627aa85dd694 into the first commit (c95225b40328c4fd9807b4b962de97627df2a15c).
And maybe rebase on master instead of merging master into this branch.

I believe this would make reviewing this PR easier.

**Pull request closed without merging**
