### PR TITLE
Fix: Increased Max-width on chapter 3 challenge 4, also removed unused flex , flex-col

### LINKED ISSUE #635: Layout issues in CH 3 Challenge 4
On the left, you can see the text budging directly against the percentage boxes, and text sticking outside of its container. On the right, the first avatar is much smaller than the others causing inconsistencies.

The second issue is probably caused by applying a fixed with to the labels ("Hashrate", "Blocks found"...). Not a good approach, it's much better to relay on [flex layout](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) to space things correctly.

The user boxes have a max-width of 220, which should be 300 per Figma. That will also help fit in all the content and prevent layout issues.

Frame 1

I also see a bunch of unnecessary Tailwind classes again. For example, a text paragraph with `flex` and `flex-col`. Those two properties define how child elements are laid out, but text paragraphs don't have any. Doesn't break anything, just confusing and makes it harder to work with the code.

[Dev site link](https://dev.savingsatoshi.com/en/chapters/chapter-3/split-2?dev=true).

### PR DESCRIPTION
**Pull request by 0tuedon**
This PR closes #635,
Fix overflow on chapter 3 challenge 4 and remove unused flex and flex-col on paragraph.

### CODE REVIEW

**Comment by 0tuedon** [comment]
@afterburn  vercel is having some issue deploying

**Comment by ecurrencyhodler** [comment]
Thanks for submitting this pr @0tuedon! Can you update the title of the pr to describe the action the PR is taking? Also I recommend using the language "closes #635" in the description as that will automatically close the issue once this pr is merged. 

Example title: Fix overflow on chapter 3 challenge 4 and remove unused flex and flex-col on paragraph.

**Comment by 0tuedon** [comment]
> Thanks for submitting this pr @0tuedon! Can you update the title of the pr to describe the action the PR is taking? Also I recommend using the language "closes #635" in the description as that will automatically close the issue once this pr is merged.
> 
> Example title: Fix overflow on chapter 3 challenge 4 and remove unused flex and flex-col on paragraph.

ACK, would change that.

**Comment by ecurrencyhodler** [comment]
Hmmm I'm running into the save blocker as before. I can't move past ch.3 intro-1. :( 

@benalleng what worked for you?

**Comment by benalleng** [comment]
We'll need to merge #644 to see those errors disappear

**Comment by ecurrencyhodler** [comment]
@0tuedon can you rebase your pr? I'll try again after.

**Review by afterburn — APPROVED** [review]

**Comment by 0tuedon** [comment]
> Hey @0tuedon I accidentally started a thread in the issue, but here is feedback from christoph.:
> "Yes, looks better. There is a layout jump that happens when pressing the first "Tell me more" on certain screen sizes. Looks like up to that point, the width setting is different than after. It would be great to fix it so the layout is consistent and this jump does not occur."

Alright would check that out.

**Comment by 0tuedon** [comment]
@ecurrencyhodler, i did make an update to fix the skip issue. WDYT? @GBKS

**Comment by ecurrencyhodler** [comment]
Thanks for fixing the skip issue! The values no longer overlap but the space seems really wide inside the box. 

Also tagging @GBKS to review.
wide

**Comment by 0tuedon** [comment]
> Thanks for fixing the skip issue! The values no longer overlap but the space seems really wide inside the box. 
> 
> Also tagging @GBKS to review.
> wide
> 

Yh @ecurrencyhodler, i think the previous issue was that it wasn't using the whole box and was just taking the max content,  hence the skip when the content is increased

**Comment by GBKS** [comment]
Thanks for fixing the skip, it's gone now.

I noticed a couple more visual things to tweak. Totally cool to do those in a separate PR.

image

There are still some fixed widths in the code. Those will likely cause layout issues when text size changes with localizations.

**Review by afterburn — APPROVED** [review]

**Comment by afterburn** [comment]
Created a new issue for the remaining visual tweaks in #660

**Pull request merged**
