### PR TITLE
Load default avatar for not logged in users

### LINKED ISSUE #94: Site crashes on first page load
**Describe the bug**
Site crashes on first page load. Refreshing the page fixes the problem.

**To Reproduce**

1. Open home page in incognito mode

**Screenshots and/or logs**

Screenshot 2023-01-20 at 11 34 56 AM

Screenshot 2023-01-20 at 11 40 01 AM

### PR DESCRIPTION
**Pull request by satsdev**
Fix for site crashing immediately after load

Resolves #94 

## Pull Request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build was run locally and any changes were pushed
- [x] Lint has passed locally and any fixes were made for failures

## Pull Request type

Please check the type of change your PR introduces:

- [x] :bug: Bugfix
- [ ] :sparkles: Feature
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :wrench: Other (please describe):

## What is the current behavior?

Site crashes shortly after load.

## What is the new behavior?

Site does not crash.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vinayaksh42** [comment]
Tested the vercel-preview link in incognito mode, and the site is not crashing. Great fix!

**Comment by GBKS** [comment]
This PR does not address the core issue and breaks the dynamic avatar display for registered users.

The main problem is that the login modal should only ever be shown if the user has actually registered - by going through the signup modal. That means that an avatar was selected and saved, and should be available in the login modal.

I am curious what the root cause here is...

**Comment by satsdev** [comment]
@GBKS Thank you for the catch. I can work on the logic. But, for your assumption, my understanding is that LoginModal will still get rendered even if it isn't displayed since it is included in NavBar. Is that not expected?

image

**Comment by satsdev** [comment]
I amended the commit with better logic that I believe preserves the saved user avatar state as you expected. Instead of passing 1, I let that decision be determined in the Avatar component.

If there is still more to this, let me know.

**Review by GBKS — APPROVED** [review]
ACK. Thanks for the update.

We still need to find out why the login modal is shown in the first place without an `avatar` being defined in the `user` object in local storage. I wonder if this has to do with us having a bit of a broken user management logic until recently, maybe this is already fixed and can't happen for completely new visitors to the site... well, we'll find out.

**Pull request merged**
