### PR TITLE
Adds a tooltip component

### PR DESCRIPTION
**Pull request by GBKS**
This is pretty freely configurable in terms of positioning. I'm implementing it here in the challenge nav bar. Users can hover each numeric challenge indicator to see the challenge number and name in the tooltip. This tip will also be used later in other elements. [Design reference](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=161%3A1652&t=VubbnftQhEW3LAXK-1).

[Check the preview](https://saving-satoshi-git-feature-tooltip-component-saving-satoshi.vercel.app/chapters/chapter-1/genesis)

A later improvement to the tooltip could be to more precisely position the arrow when left/right/top/bottom aligning with the reference element.

## Pull Request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build was run locally and any changes were pushed
- [x] Lint has passed locally and any fixes were made for failures

## Pull Request type

- [ ] :bug: Bugfix
- [x] :sparkles: Feature
- [ ] :lipstick: :art: Code style update (formatting, renaming)
- [ ] :recycle: Refactoring (no functional changes, no api changes)
- [ ] :zap: Performance
- [ ] :pencil: Documentation content changes
- [ ] :wrench: Other (please describe):

### CODE REVIEW

**Review by satsie — APPROVED** [review]

**Review by aureleoules — APPROVED** [review]
Looks good!
I suggest adding the diff below. The tooltip will show up with a transition.

<details>
<summary>Git diff</summary>

```diff
diff --git a/components/ui/Tooltip.tsx b/components/ui/Tooltip.tsx
index cbf840f..e849dde 100644
--- a/components/ui/Tooltip.tsx
+++ b/components/ui/Tooltip.tsx
@@ -31,7 +31,7 @@ export const Tooltip = ({
     show: boolean,
     position?: string
   }) => {
-    let classes = 'absolute bg-black border border-white pointer-events-none shadow-lg shadow-black/25'
+    let classes = 'absolute bg-black border border-white pointer-events-none shadow-lg shadow-black/25 transition-all duration-200'
     let arrowDirection = null
     let arrowClasses = "relative flex flex-col items-center px-5 py-2 after:content-[''] after:w-3 after:h-3 after:absolute after:bg-black"
 
@@ -98,7 +98,7 @@ export const Tooltip = ({
     return (
       <div
           className={clsx(classes, {
-            'hidden': !show,
+            'opacity-0': !show,
           })}
         >
         <div className={arrowClasses}>
```

</details>

**Comment by GBKS** [comment]
@aureleoules thanks for the suggestion. A problem with `opacity: 0` is that the element is still rendered even when not visible. Screen readers will pick it up, and it can be accessed via keyboard tabbing. This is not the case with `visibility: hidden` (which is what `hidden` does).

An ideal solution is that the element is not rendered at all when it's not visible, and also has fade in/out when appearing/disappearing. [VueJS](https://vuejs.org/guide/built-ins/transition.html) does this automatically with the `transition` tag, but I have not looked into how to do this in React. Was going to come back to this later at some point. Do you maybe know?

**Comment by aureleoules** [comment]
Ah I see. I haven't tested but maybe this could do it: https://reactcommunity.org/react-transition-group/transition.

**Comment by aureleoules** [comment]
Nice, this looks good.
Just a nit: I suggest removing the package-lock.json as there is already the yarn.lock file, which may be confusing.

**Review by aureleoules — APPROVED** [review]

**Comment by GBKS** [comment]
I just implemented this using the [CSSTransition](http://reactcommunity.org/react-transition-group/css-transition) component.

Gotta say, this code is super ugly. And I fully blame it on React and Tailwind for rejecting much of the elegance of CSS.

**Pull request merged**
