### PR TITLE
Challenge Complete page location

### LINKED ISSUE #283: First Challenge Complete page in the wrong location
Following the completion of the first challenge there is no special page congratulating me!
[This page](https://savingsatoshi.com/en/chapters/chapter-1/genesis-4) needs to be moved just before the terminal challenge based on its copy. Also calls into question our use of terms, chapter -> challenge -> task/problem?

### PR DESCRIPTION
**Pull request by vinayaksh42**
Fixes #283

### CODE REVIEW

**Comment by vinayaksh42** [comment]
based on the recent discussion in issue #283, the challenge completion page will remain after the genesis-terminal Challenge.

**Comment by ecurrencyhodler** [comment]
Hey @vinayaksh42 if you wanna open this back up, Christoph suggested moving the page and provided additional copy.

**Comment by ecurrencyhodler** [comment]
Check his latest comments in https://github.com/saving-satoshi/saving-satoshi/issues/283

**Comment by vinayaksh42** [comment]
> Hey @vinayaksh42 if you wanna open this back up, Christoph suggested moving the page and provided additional copy.

I think i misunderstood the comment, I have reopened the PR

**Comment by ecurrencyhodler** [comment]
Ooof I'm sorry. I got confused as well. His updates in figma only require copy changes. We can handle that in a separate PR.

**Pull request closed without merging**
