### PR TITLE
Styling fix for initial state of scripting challenge

### PR DESCRIPTION
**Pull request by vinayaksh42**
fixes: #339

[preview](https://saving-satoshi-git-fork-vinayaksh42-issue339-saving-satoshi.vercel.app/en/chapters/chapter-2/scripting-2?dev=true)

### CODE REVIEW

**Review by afterburn — CHANGES_REQUESTED** [review]
Code looks fine, but I noticed that the loading state of the runner looks like this:
image

While the loaded state looks like this:
image

Would be nice to have them be the same height.

**Comment by afterburn** [comment]
Thanks @vinayaksh42 the height of the loader is now the same as the idle state of the Runner. I don't think this PR fixes #339 though, because there still is the "Custom validation message" which should be dynamically changed based on the current hash that is being validated. If you want to work on that issue in this PR feel free, otherwise let me know and we can merge this but keep #339 open.

**Review by afterburn — APPROVED** [review]

**Comment by vinayaksh42** [comment]
> Thanks @vinayaksh42 the height of the loader is now the same as the idle state of the Runner. I don't think this PR fixes #339 though, because there still is the "Custom validation message" which should dynamically change based on the current hash that is being validated. If you want to work on that issue in this PR feel free, otherwise let me know and we can merge this but keep #339 open.

Sure, I will create a new PR for adding the "custom validation message"

**Comment by afterburn** [comment]
@vinayaksh42 its okay I fixed this in #398

**Pull request merged**
