### PR TITLE
Add object-position to all Intros

### LINKED ISSUE #618: Size of images should focus on top when window is smaller.
When I make the width of the screen smaller, the website focuses on the bottom of the image. IMO it makes more sense for it to focus on the top. But I'd like @GBKS to take a look and provide some guidance on how to handle situations like this.

This is for the chrome browser on mac.

Screenshot 2023-09-03 at 12 29 51 PM

Dimensions were :1300 x 672

This issue is not a blocker for release.

### PR DESCRIPTION
**Pull request by benalleng**
Closes #618

[Chapter 1](https://saving-satoshi-git-fork-benalleng-issue618-savingsatoshi.vercel.app/en/chapters/chapter-1/intro-1?dev=true)
[Chapter 2](https://saving-satoshi-git-fork-benalleng-issue618-savingsatoshi.vercel.app/en/chapters/chapter-2/intro-1?dev=true)
[Chapter 3](https://saving-satoshi-git-fork-benalleng-issue618-savingsatoshi.vercel.app/en/chapters/chapter-3/intro-1?dev=true)

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Hmm it still seems to go to the bottom of the image rather than the top.
Screenshot 2023-09-11 at 6 35 07 PM

**Comment by benalleng** [comment]
hmm seems to work in firefox for me, but on chrome I come across the same problem that it is crashing...

**Comment by ecurrencyhodler** [comment]
I'm unable to do it in both firefox and chrome on mac.

Chrome logs:
Screenshot 2023-09-12 at 10 20 21 AM

Firefox logs:
Screenshot 2023-09-12 at 10 21 24 AM

**Comment by ecurrencyhodler** [comment]
ch. 1 and ch. 2 intros look great across various sizes. 

Ch. 3 intro also looks but except for this area. IMO the focus should be higher. Like his face.
Screenshot 2023-09-15 at 3 28 17 PM

**Comment by benalleng** [comment]
@ecurrencyhodler not a lot of precision with object positions unfortunately, changed it to be focused towards the top more, let me know what you think

**Comment by ecurrencyhodler** [comment]
Better! Thanks.

**Review by ecurrencyhodler — APPROVED** [review]
tACK!

**Review by afterburn — APPROVED** [review]

**Pull request merged**
