### PR TITLE
Input class

### LINKED ISSUE #767: Chapter 6 Challenge 1 Input Class
Implement the first challenge page for chapter 6

image

https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=6200%3A11239&mode=dev

### PR DESCRIPTION
**Pull request by benalleng**
Closes #767 

Validation works on both JS and Python

also made a change where there were some misordered challenges `in-out-4` <=> `in-out-5`

also added a continue button in `in-out-1` where there was none

[Preview](https://saving-satoshi-git-fork-benalleng-issue767-savingsatoshi.vercel.app/en/chapters/chapter-6/in-out-4?dev=true)

### CODE REVIEW

**Comment by daviroo** [comment]
Looks good although there is no help page for this challenge - is that something which we are planning to add in a separate PR?

**Comment by benalleng** [comment]
yes, I'm intending to add help pages seperately

**Comment by 0tuedon** [comment]
Screenshot 2024-01-23 at 20 52 59
Currently having issues on the python challenge

**Comment by benalleng** [comment]
I think that is an error in the `answer.py` file. I reference it in this issue https://github.com/saving-satoshi/challenges/issues/7

**Review by daviroo — APPROVED** [review]

**Pull request merged**
