### PR TITLE
Slow hashrateChallenge and fix unique key errors

### PR DESCRIPTION
**Pull request by benalleng**
This PR slows down the hashRateChallenge slightly and fixes some key prop errors in chapter 3

[Preview](https://saving-satoshi-git-fork-benalleng-hashchal-4f1c73-savingsatoshi.vercel.app/en/chapters/chapter-3/solo-1?dev=true)

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Hmm...I can't seem to unlock ch.3 to test.

**Review by afterburn — APPROVED** [review]

**Comment by afterburn** [comment]
@ecurrencyhodler that would be due to the VERCEL preview using the feature flag system, which currently says chapter 3 should be disabled. We can either spin up a separate database for our `dev` environment, or we could add some query parameter that lets you bypass feature flags. I think the latter is less work, but we should create a separate issue for this.

**Comment by afterburn** [comment]
PR for the above here: https://github.com/saving-satoshi/saving-satoshi/pull/601

**Comment by ecurrencyhodler** [comment]
@afterburn should we just merge this? Or should ben rebase for me to test?

**Comment by benalleng** [comment]
I can rebase it

**Comment by ecurrencyhodler** [comment]
Okay I think kevin's pr is still open. Can you review it? Then rebase after I merge his?

**Comment by ecurrencyhodler** [comment]
tack!

**Pull request merged**
