### PR TITLE
Add onClick() to avatar button for accessibility

### LINKED ISSUE #525: Screen persists after entering in my own secret to save progress
The screen persists after entering in my own secret to save my progress. 

But the good news is that I tried logging in using the secret I entered before and it does get saved to our database and my progress does get saved.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/3ec75329-0a96-4fe4-9ee1-c2ccecc05adb

### LINKED ISSUE #528: Move `onClick` function to the button
The `onClick` function still has to be moved to the button, as I pointed out multiple times. It cannot be on the image.

When I use VoiceOver right now, I can highlight the different avatars. From a technical perspective, the button element is highlighted (not the image). But pressing does not do anything. That's because the `onClick` is not on the button. 

`key={i}` can also be removed from the Avatar, since the mapping happens on the button element.

_Originally posted by @GBKS in https://github.com/saving-satoshi/saving-satoshi/issues/499#issuecomment-1600235744_

### PR DESCRIPTION
**Pull request by benalleng**
Closes #528, Closes #525

This also fixes some stray sizing errors, should now look like the original selector while behaving with the new logic

### CODE REVIEW

**Comment by benalleng** [comment]
Turn on sound

[Kazam_screencast_00000.webm](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/6b4a3745-a95e-4a04-9c16-b7389992f2fb)

**Comment by ecurrencyhodler** [comment]
Thanks for the video. Should we actually describe the logo a bit rather than calling it Logo 1/2/3/4? @GBKS 

EG: 

- Select avatar of a person in a white space suit.
- Select avatar of a person in an orange space suit.
- Select avatar of a person in a orange-ish red space suit with the sun reflecting off it.
- Select avatar of a bunny in a white space suit without a helmet.
- Select avatar of a badger in a white space suit without a helmet.

**Comment by benalleng** [comment]
I think more simplicity is ideal here
- White space-suit
- red space-suit
- orange space-suit
- bunny engineer
- badger astronaut

**Comment by ecurrencyhodler** [comment]
I'm cool with that. @GBKS thoughts?

**Review by afterburn — APPROVED** [review]

**Comment by ecurrencyhodler** [comment]
I think this was merged prematurely. 

@GBKS if you can still provide your thoughts on how to name the profiles, I'll create another issue and we can address it in a separate pr.

**Comment by GBKS** [comment]
Good idea to give them distinct names. I'd like to revise those avatars at some point altogether to give more options and to better match the visual style to the site (I took the current ones from Alexa's Figma library).

**Pull request merged**
