### PR TITLE
Chapter 4 Address 3

### LINKED ISSUE #626: Implement CH4 Challenge 2 - Address generation
Use the `ScriptingChallenge` component to implement chapter 4 challenge 2. For our lesson IDs we can use `CH4AD1` and `CH4AD2`.

[Link to Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?type=design&node-id=1535-19614&mode=design&t=bUUrHbu3heWV0c7c-0)

Is currently blocked by https://github.com/saving-satoshi/saving-satoshi/issues/624

### PR DESCRIPTION
**Pull request by benalleng**
Closes #626
The final challenge for chapter 4

[Preview](https://saving-satoshi-git-fork-benalleng-address-2-savingsatoshi.vercel.app/en/chapters/chapter-4/address-3?dev=true)

### TODO
- ~~how to handle an non-signed-in user~~ (we should hande this in a future PR

### CODE REVIEW

**Comment by daviroo** [comment]
Hey @benalleng.  I spent some time this morning reviewing this change - mostly by stepping through chapter 4 (I haven't reviewed the code in depth yet).  I did find some issues with it which I think might need fixed before pushing them live (some are minor and could be left but some are blockers I think).

- public key 2 text says "On the right" but on mobile image is at the top.
- public key challenge 1 text says "(find out why)" but there is no hyperlink.
- public key challenge 1 text says "(learn more)" but there is no hyperlink.
- public key challenge 1 text says "complete the function `privatekey_to_publickey()`" but this function does not exist. (perhaps should say "create the function")
- There was a bug in the code editor where I couldn't enter any input on the last 2 lines of the editor e.g. I had lines 11-14 blank (new lines) but I couldn't enter any text into lines 13/14.
- The solution for challenge 1 did not include the step to turn private key into integer
- I found challenge 1 to be particularly hard
- Public key challenge 2 solution "# The hext string then needs to be encoded into bytes" (misspelled hex)
- Public key challenge 2 it's impossible to modify the start of the function
- Public key challenge 2 example solution does not have steps for converting hex values of x,y to integers
- Address challenge 2 example says "Complete the function `hash_compressed()`" but this function doesn't exist
- Address challenge 2 solution includes compressedPublicKey var which is undefined
- Address challenge 3 says "Call the provided `hash_to_address()` function with your data to generate your Bitcoin address!" but this function doesn't exist.
- Address challenge 3 solution seems to be unimplemented
- Address challenge 3 print out literal "chapter_two.address_three.success" on success.

**Comment by benalleng** [comment]
> public key 2 text says "On the right" but on mobile image is at the top.

We've run into this issue in the past, generally we've decided to slightly alter the copy to make it make sense in a mobile context and on desktop

**Comment by benalleng** [comment]
> There was a bug in the code editor where I couldn't enter any input on the last 2 lines of the editor e.g. I had lines 11-14 blank (new lines) but I couldn't enter any text into lines 13/14. Handled by #697

**Comment by benalleng** [comment]
the undefined vars likely have to do with being unable to read data from the backend, are you logged in?

**Review by daviroo — APPROVED** [review]

**Comment by daviroo** [comment]
> Hey @benalleng. I spent some time this morning reviewing this change - mostly by stepping through chapter 4 (I haven't reviewed the code in depth yet). I did find some issues with it which I think might need fixed before pushing them live (some are minor and could be left but some are blockers I think).
> 
> * [x]  public key 2 text says "On the right" but on mobile image is at the top.
> * [x]  public key challenge 1 text says "(find out why)" but there is no hyperlink.
> * [x]  public key challenge 1 text says "(learn more)" but there is no hyperlink.
> * [x]  public key challenge 1 text says "complete the function `privatekey_to_publickey()`" but this function does not exist. (perhaps should say "create the function")
> * [x]  There was a bug in the code editor where I couldn't enter any input on the last 2 lines of the editor e.g. I had lines 11-14 blank (new lines) but I couldn't enter any text into lines 13/14.
> * [x]  The solution for challenge 1 did not include the step to turn private key into integer
> * [x]  Public key challenge 2 solution "# The hext string then needs to be encoded into bytes" (misspelled hex)
> * [x]  Public key challenge 2 it's impossible to modify the start of the function
> * [x]  Public key challenge 2 example solution does not have steps for converting hex values of x,y to integers
> * [x]  Address challenge 2 example says "Complete the function `hash_compressed()`" but this function doesn't exist
> * [x]  Address challenge 2 solution includes compressedPublicKey var which is undefined
> * [x]  Address challenge 3 says "Call the provided `hash_to_address()` function with your data to generate your Bitcoin address!" but this function doesn't exist.
> * [x]  Address challenge 3 solution seems to be unimplemented
> * [x]  Address challenge 3 print out literal "chapter_two.address_three.success" on success.
> 
> Some of these aren't directly related to this PR but instead around chapter 4 in general.

Looks like these are all taken care of so I have approved 👍

**Pull request merged**
