### PR TITLE
Add temp foss banner

### LINKED ISSUE #802: Add Start Career in FOSS Banner
See here: https://github.com/bitcoin-dev-project/bitcoin-dev-project/issues/27

### PR DESCRIPTION
**Pull request by 0tuedon**
This PR closes #802 , Although we may need to have discussion if the banner design is okay

### CODE REVIEW

**Comment by GBKS** [comment]
Here's a mock-up for the design. What do you think?

image

**Comment by GBKS** [comment]
You could also place it at the very top above the navigation. I really would avoid placing it over the image though, because it easily covers up the eyes/face, especially on mobile where the spacing is really tight.

image

**Comment by 0tuedon** [comment]
> You could also place it at the very top above the navigation. I really would avoid placing it over the image though, because it easily covers up the eyes/face, especially on mobile where the spacing is really tight.
> 
> image

No need for a close icon then ?

**Comment by GBKS** [comment]
No need to close it if it doesn't cover anything up. Also, this will be only on the home page, right? No other pages.

**Comment by 0tuedon** [comment]
> No need to close it if it doesn't cover anything up. Also, this will be only on the home page, right? No other pages.

yh updated with a new commit

**Comment by adamjonas** [comment]
I'd like to put a hold on this. I don't think this is the target audience for this and we've had plenty of applications already. 

Secondarily, the current implementation on mobile becomes the focus rather than an announcement. I'd prefer this effort be put towards other features.

**Pull request closed without merging**
