### PR TITLE
Allow terminal answer with extra whitespace to be marked correctly

### PR DESCRIPTION
**Pull request by shaavan**

### CODE REVIEW

**Comment by shaavan** [comment]
This PR address [this](https://github.com/saving-satoshi/saving-satoshi/issues/287#issuecomment-1465655373) comment by @GBKS 

> I also noticed this one. Also saw that an extra space at the end of of a command makes it incorrect. Can we maybe add some trimming?

**Comment by GBKS** [comment]
That was quick! Trim only removes white space from start and end? Or does it do anything else also (just not familiar with the details of the function)?

**Review by afterburn — CHANGES_REQUESTED** [review]
Doesn't seem to work quite right:
image

1. I entered " 5361746f7368693433335061726b53744368696e6f43413933323433".
2. I entered "5361746f7368693433335061726b53744368696e6f43413933323433 ".
3. I entered "5361746f7368693433335061726b53744368696e6f43413933323433".
4. I entered "5361746f7368693433335061726b53744368696e6f43413933323433 " (again).

**Comment by shaavan** [comment]
@afterburn 

This PR addresses @GBKS's comment, which states.

> ...extra space at the end of a command makes it incorrect.

This PR checks for when the extra spaces are present within the command.
But that would be a useful addition to this PR!

@GBKS 

> Trim only removes white space from start and end? Or does it do anything else also?

The **Trim** function only removes the whitespace around the string and does not affect the original string. Here's a [reference](https://www.w3schools.com/jsref/jsref_trim_string.asp).

**Comment by shaavan** [comment]
Updated from cac2537d03c90e2fbb9d35f16a3effaae5e9e341 to a047a9d94804250c7446bf28fa809123258bc89b ([pr293.01](https://github.com/shaavan/saving-satoshi/commits/pr293.01) -> [pr293.02](https://github.com/shaavan/saving-satoshi/commits/pr293.02), [diff](https://github.com/shaavan/saving-satoshi/compare/pr293.01..pr293.02))
Addressed @afterburn suggestion

1. Updated code so that commands with extra whitespace within themselves will also be correctly evaluated.

**Comment by afterburn** [comment]
@shaavan Ah sorry I must have misunderstood the original ticket. Thanks!

**Review by afterburn — APPROVED** [review]

**Pull request merged**
