### PR TITLE
CodeExample optional copy

### PR DESCRIPTION
**Pull request by benalleng**
Enhances the `CodeExample.tsx` component to allow for optional copy/paste as well as wraps the code better for mobile. without the copy button present this could help the user interactions on code examples where there has been confusion on what "should" be directly copied and what should be adjusted to fit the code challenge. Will generally help with UX

## Pull Request checklist

Please review the below PR requirements:

- [x] Build was run locally and any changes were pushed
- [x] Ensure that the title clearly describes the changes
- [x] Issue to be referenced in the PR description rather than in the commits or PR title
- [x] Clean commit history
TODO: decide what each code example should look like in their respective routes. 
As an example `echo ScriptSigHex | xxd -r -p` probably should not have the copy button enabled as the user should not copy this code verbatim

### Terminal Challenge 2 (no copy)
image

### Transaction Challenge 1 (copy)
image

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Tested and it works! I actually really like the update. It's pretty clear.
copy:paste

Also assigning a design review to christoph.

**Comment by vinayaksh42** [comment]
The next button disappears when I complete this challenge - https://saving-satoshi-git-fork-benalleng-mobilec-3bc8f9-saving-satoshi.vercel.app/chapters/chapter-1/genesis-2, not sure if this bug is part of this PR as it is not changing any of the code associated with `StatusBar`. Although in a recent PR #125, I added the mobile view for terminal-based challenges, the bug may go away if you update the branch you are working on.

**ScreenShots**
Current View:
Screenshot 2023-02-07 at 6 25 40 AM

This PR:
Screenshot 2023-02-07 at 6 25 24 AM

**Comment by GBKS** [comment]
@benalleng thanks for this update, I tested and reviewed the code and it looks good. 

@ecurrencyhodler your screenshot does not show what Ben worked on in this PR, you may not have tested the right thing. For future PRs, it would be amazing to have a "Preview" link in the PR description to the exact page that the code changes affect. We do this in the design guide ([example](https://github.com/BitcoinDesign/Guide/pull/977)) and it makes testing lots easer (no digging around).

@vinayaksh42 there seem to be a lot of issues with the mobile layout. Not sure if it's outdated code or anything else, but that seems like a separate issue or PR.

**Comment by vinayaksh42** [comment]
> @benalleng thanks for this update, I tested and reviewed the code and it looks good.
> 
> @ecurrencyhodler your screenshot does not show what Ben worked on in this PR, you may not have tested the right thing. For future PRs, it would be amazing to have a "Preview" link in the PR description to the exact page that the code changes affect. We do this in the design guide ([example](https://github.com/BitcoinDesign/Guide/pull/977)) and it makes testing lots easer (no digging around).
> 
> @vinayaksh42 there seem to be a lot of issues with the mobile layout. Not sure if it's outdated code or anything else, but that seems like a separate issue or PR.

The branch on which @benalleng is working on  seems to be missing the `TerminalChallenge.tsx` file, so it's most probably due to outdated files. - https://github.com/benalleng/saving-satoshi/tree/mobileCodeLayout/ui/lesson

**Comment by GBKS** [comment]
@vinayaksh42 good catch. @benalleng might be good to update your branch to ensure there are no conflicts.

**Comment by benalleng** [comment]
@GBKS @vinayaksh42 thanks for pointing that out, I must've started this before #125 and #126 were merged. I apologize for the confusion on what this code does! It only changes whether the codeExample is able to be copied to the clipboard to prevent the user from copying code where they should instead change it to their own input.

[No Copy Preview](https://saving-satoshi-e4ui69puu-savingsatoshi.vercel.app/chapters/chapter-1/genesis-2)

[Copy Preview](https://saving-satoshi-e4ui69puu-savingsatoshi.vercel.app/chapters/chapter-1/transacting-1)

After watching the [youtube video](https://youtu.be/94R-XbNRrS8) I think it is best to change exactly which routes use the copy and paste functionality of the code example if we want 'which we should' to have the difficulty increase as the user completes lessons. 
I am going to change to a draft until I think it is utilized correctly in all of the respective routes

**Comment by benalleng** [comment]
Closing in lieu of #143

**Pull request closed without merging**
