### PR TITLE
Top padding error in Pool-3 / Split-2

### LINKED ISSUE #621: Text box in success status is too large for chapter-3/pool-3
Once the mining challenge is complete for chapter-3/pool-3, the success text box and button is expanded making it too large. This is for the chrome browser on mac.
Screenshot 2023-09-03 at 12 45 26 PM

When we look at the previous challenge, we see that the "continue" button still has space at the bottom. This might be a text font issue. If not, I recommend making the text box limits wider.
Screenshot 2023-09-03 at 12 47 02 PM

### PR DESCRIPTION
**Pull request by benalleng**
Closes #621 

need some testing on this one as I've found we have some wide range of screen sizes som I'm not sure what everyone's default screen looks like

### CODE REVIEW

**Comment by ecurrencyhodler** [comment]
Ugh. I can't test this one either cuz I can't get past intro-1.

**Comment by ecurrencyhodler** [comment]
Lesson 2 and Lesson 3 look great.
Screenshot 2023-09-15 at 3 12 45 PM
Screenshot 2023-09-15 at 3 13 20 PM




Lesson 1 seems to have a weird formatting issue. Continue button is cut off. Was the introduced in this pr?
Screenshot 2023-09-15 at 3 12 02 PM

**Comment by benalleng** [comment]
didn't mess with solo-1 but I should be able to fix that too

**Comment by ecurrencyhodler** [comment]
okay appreciate that.

**Review by afterburn — APPROVED** [review]

**Comment by benalleng** [comment]
@ecurrencyhodler Need another test, Big rebase and I want to make sure its right

**Comment by ecurrencyhodler** [comment]
tACK! Everything was well sized and in frame. There are a couple of sections in Challenge 3 where the "tell me more" was slightly off but it's not a big deal IMO. Great work Ben.
liloff

**Pull request merged**
