### PR TITLE
Change blocks found amount found for coop-2, made player the on to find blocks

### LINKED ISSUE #581: Change progress of characters in Ch. 3 Co-op vs Bitrey (Lose)
In this section, it looks like only the blue miner is doing work and progressing. We should split this up more evenly across contributors. Let's reference the % distribution in #579.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/023d45d4-ca7e-47fd-9bd3-4a7a1a80fb1b

_Originally posted by @ecurrencyhodler in https://github.com/saving-satoshi/saving-satoshi/pull/570#pullrequestreview-1546364979_

### PR DESCRIPTION
**Pull request by afterburn**
Resolves #581, set the blocks found amount to 0 for 3 co-op players, set the Player to be the one to find blocks.

### CODE REVIEW

**Comment by afterburn** [comment]
@ecurrencyhodler I see, so basically what it was like before? https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?type=design&node-id=4102-48738&mode=design&t=IMDBZhgluqy77skG-4

If the intention is to be able to have the remaining 3 players have 0 blocks found, but still be visible on the ProgressBar, I can make this fix in the ProgressBar component itself. So when we pass it 0 blocks found, it will still render something for the player. Please confirm if this is the intended goal.

**Comment by ecurrencyhodler** [comment]
Yeah the main thrust of the issue is to reorder the characters in Ch. 3 Co-op vs Bitrey in the progress bar. Hash hoppers should be the last ones on the right winning blocks. The other hashers are visible and are on the left with 0 blocks.

Thanks.

**Comment by benalleng** [comment]
This is code from me, I added the other miners getting individual blocks and editing the numbers for the user so it appeared on the contribution bar but did not show them as having blocks, this was the purpose of the ternaries `value: step == 0 ? 0 : 1`.  When I made this I wasn't sure how the contribution bar functioned and I decided to go with the approach to edit the profiles instead.

If you want to adjust the `contributionBar` to work this way that would definitely work too and probably make more sense on the content page!

As for the intention of the issue, I think it was just to rearrange the `PROTAGONISTS[]` like @ecurrencyhodler mentioned

**Comment by afterburn** [comment]
@ecurrencyhodler @benalleng ready for another review

**Comment by ecurrencyhodler** [comment]
tACK! Great work kevin. Thanks.
Screenshot 2023-08-23 at 3 34 25 PM

**Review by ecurrencyhodler — APPROVED** [review]

**Pull request merged**
