### PR TITLE
scripting validation for chapter 2 and success message

### PR DESCRIPTION
**Pull request by benalleng**
This moves the scripting challenge success messages into the content page instead of as a parameter that drills down to the ui component.

Also changes the validation of chapter 2 scripting 2 to see if there is a better flow to requiring the nonce value to prevent users from console.logging a string with all zeroes

[Preview chapter 2 validation change](https://saving-satoshi-git-fork-benalleng-chapter-162acc-savingsatoshi.vercel.app/en/chapters/chapter-2/scripting-2?dev=true)

[Preview translation success message moved](https://saving-satoshi-git-fork-benalleng-chapter-162acc-savingsatoshi.vercel.app/en/chapters/chapter-8/building-blocks-3?dev=true)

### CODE REVIEW

**Comment by 0tuedon** [comment]
Re

> Preview chapter 2 validation change

Screenshot 2024-10-31 at 12 32 57
Still get success if I just log out the value

**Review by 0tuedon — APPROVED** [review]
LGTM!, I thought console.log worked when i tried it turns our it just got the right answer

**Comment by benalleng** [comment]
You console.logged a number that hashed to 5 zeroes??

**Comment by 0tuedon** [comment]
> You console.logged a number that hashed to 5 zeroes??

no, i made a comment earlier but deleted it. i made hash to start with 4 zeros and also console a number that starts from 5 zeros. 

the function ran, and i mistook it for the one i consoled

Screenshot 2024-10-31 at 12 32 57

**Pull request merged**
