### PR TITLE
Styling fix for signed in model

### LINKED ISSUE #168: Mobile Responsive Modal: Profile screen doesn't adapt to mobile
**Describe the bug**
When I click on the profile on mobile for Chrome and Safari, the screen doesn't adapt. 

Safari
Chrome

**To Reproduce**

1. Click on profile
2. View screen in mobile

**Expected behavior**
Profile screen should adapt. Here is [the design in figma.](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1852%3A21344&t=sDLyutrdiM9Wgrid-1)
Profile screen

### PR DESCRIPTION
**Pull request by vinayaksh42**
resolves the first part of #147 and fixes #168

**Changes**
- Minor styling changes (spacing, text size)

**Screenshot**
Screenshot 2023-02-21 at 2 15 27 AM

Figma link - https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1112%3A14225&t=p997ySICoKBBYtU3-0

### CODE REVIEW

**Review by benalleng — COMMENTED** [review]
I noticed that the Modal doesn't respond to screen size.
image

Is it worth adding on some responsive design in this PR?

**Comment by ecurrencyhodler** [comment]
Tested this on web and it looks great! Thanks Vinayak!

I noticed the same thing Ben did when clicking on the profile on my mobile for both safari and chrome. 

Let's review the code for this one and merge. I'll create a separate issue for a responsive Modal.

**Comment by vinayaksh42** [comment]
@benalleng @ecurrencyhodler 
I found this [figma mockup](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1852%3A21344&t=p997ySICoKBBYtU3-0) for mobile responsive design. I think we should try and incorporate a mobile responsive modal in a separate PR as It will involve changing the other modals as well.

**Comment by ecurrencyhodler** [comment]
Created a separate issue: https://github.com/saving-satoshi/saving-satoshi/issues/168

**Comment by vinayaksh42** [comment]
> Created a separate issue: #168

I have pushed the changes required for fixing #168 as the changes required were not a lot. I have made the modal occupy the entire screen as mentioned by @GBKS in this comment - https://github.com/saving-satoshi/saving-satoshi/pull/144#issuecomment-1429667115 as well as the [figma mockup ](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1852%3A21344&t=p997ySICoKBBYtU3-0)

**Comment by ecurrencyhodler** [comment]
Awesome thanks Vinayak!

It is definitely responsive but there doesn't seem to be a lot of space at the top of the screen. Here's what it looks like on both chrome and safari. I believe figma specifies 30px padding at the top and 20 px on the sides. 

Screenshot 2023-02-20 at 1 44 49 PM

Also there is guidance on how to handle 5 profile icons in figma. Hopefully Christoph can also provide guidance on if this is how he wants to display them.

**Comment by ecurrencyhodler** [comment]
Tested on safari and chrome for mobile. Looks great!

**Comment by ecurrencyhodler** [comment]
Let's get one more code review and we can merge.

**Review by afterburn — APPROVED** [review]

**Comment by GBKS** [comment]
Chiming in a bit late. The 5 avatars should simply scroll horizontally when the modal is not wide enough. There is a [mock-up here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2019%3A22335&t=wtEGAyNRp9cwYerM-1).

**Comment by vinayaksh42** [comment]
> Chiming in a bit late. The 5 avatars should simply scroll horizontally when the modal is not wide enough. There is a [mock-up here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2019%3A22335&t=wtEGAyNRp9cwYerM-1).

@GBKS I'll create a new issue for changing the way the avatars appear in modal

**Comment by GBKS** [comment]
@vinayaksh42 awesome, thank you!

**Pull request merged**
