### PR TITLE
Remaining chapter 5 help pages

### LINKED ISSUE #742: Chapter 5 Help pages
We need to populate the resource pages for all of Chapter 5

- [ ] Derive message
- [ ] verify signature
- [ ] validate signature

### PR DESCRIPTION
**Pull request by benalleng**
Closes #742 

[derive-message-preview](https://saving-satoshi-git-fork-benalleng-chapter-d81fe0-savingsatoshi.vercel.app/en/chapters/chapter-5/derive-message-1/help)

[validate-signature-preview](https://saving-satoshi-git-fork-benalleng-chapter-d81fe0-savingsatoshi.vercel.app/en/chapters/chapter-5/validate-signature-1/help)

### CODE REVIEW

**Review by 0tuedon — CHANGES_REQUESTED** [review]
Screenshot 2023-11-17 at 22 34 58
Currently experiencing this closure

**Comment by benalleng** [comment]
Is that a consistent error, I am unable to reproduce it

**Comment by 0tuedon** [comment]
> Is that a consistent error, I am unable to reproduce it

Screenshot 2023-11-17 at 22 34 58
Yh,  kept refreshing and it kept coming back let me try a larger screen
Screenshot 2023-11-17 at 22 38 48
r

**Comment by 0tuedon** [comment]
Screenshot 2023-11-17 at 22 40 29
looks quite okay on a larger screen. but on smaller ones it squishes

**Review by 0tuedon — APPROVED** [review]
LGTM! the height  of the editor works now

**Pull request merged**
