### PR TITLE
Block locked challenges

### LINKED ISSUE #155: Block navigation to locked challenges
**Describe the bug**
Users are currently able to navigate to any challenge, even if they haven't unlocked it yet.

**To Reproduce**
Using a fresh account either go to the first Genesis page, then click on the Transacting challenge in the Navbar or go to [this url](https://savingsatoshi.com/en/chapters/chapter-1/transacting-1) directly.

**Expected behavior**
Users should only be able to navigate to challenges that they have unlocked. If they try to navigate to a locked challenge we should either show a "This challenge is locked" message or redirect them back to either chapter overview or the last challenge that they have unlocked.

### PR DESCRIPTION
**Pull request by gadabra**
Fix #155.  
I have opened this request so that we can discuss on here. My solution currently looks like this, but is not complete. I am aiming to finish it within a few hours or by tomorrow morning; 

to do this
- I will create a `checkChallengeAllowed` function in `useContentRoute` and 
- call `checkChallengeAllowed` before every challenge page is opened.

### CODE REVIEW

**Comment by gadabra** [comment]
I ran through all the scenarios in my head and it seems to be working. If you come across any that have issues, I can work on resolving them. I am considering changing the naming or placement of ProtectRoute and such. Is there any feedback, review that I can work on?

**Review by shaavan — COMMENTED** [review]
@gadabra 

I am not able to navigate further from the genesis-1 page.

https://saving-satoshi-j877rqzjd-savingsatoshi.vercel.app/en/chapters/chapter-1/genesis-1

Clicking the continue button does not direct me to the next page.

**Comment by afterburn** [comment]
In the top-right tabs we should not render a `<Link>` if the user has not unlocked that particular challenge yet.

**Comment by afterburn** [comment]
Hey @gadabra, please resolve the conflicts if you have time today

**Comment by gadabra** [comment]
I tried to solve comments.

- (https://github.com/saving-satoshi/saving-satoshi/pull/282#pullrequestreview-1337075795) I added user progress function to next, continue buttons 
- (https://github.com/saving-satoshi/saving-satoshi/pull/282#issuecomment-1466721597) I added CSS property to disable link.

**Comment by ecurrencyhodler** [comment]
Re-opening. Saba doesn't have an issue with gadabra closing the issue out.

**Comment by benalleng** [comment]
TACK! The locked buttons work great, still needs a merge from master to work with the updated challenge scheme

**Comment by gadabra** [comment]
I attempted to merge with the master branch, but I made a mistake. I had made it so that every 'next' button saved the user's progress, which resulted in challenges being unlocked when the user attempted to solve them again. To prevent this, I need to find a way to save progress only when the user looks at it again.

 Furthermore, I would like to ask how the progress should be saved. Should it be done in every 'next' button, like I implemented, or should we create a table or map to show which lessons the progress should be saved for, and which lessons the user can access after that saving?

**Comment by benalleng** [comment]
Hmm, that's a good question!

I think ideally progress should be saved on <ins>challenge completion</ins> however, i recognize this may create a lot of hassle changing this so late with you likely needing to change the logic to match the trigger of the status bar showing completion.
Like you said, if I complete a challenge but then quit after completing it I should not have to do that challenge again. (perhaps it was very difficult and now I want a break without going to the next challenge)

However, with the upcoming changes and implementing a backend I think that this change is not worth it! Ultimately we will be refactoring user progress to be stored on the backend and I do not want you to have to rewrite your code only to have it replaced again!

**Comment by ecurrencyhodler** [comment]
@gadabra can you work with Ben to resolve the conflicts so we can merge? Then we can refactor it once we get a backend deployed.

**Comment by ecurrencyhodler** [comment]
closing this as gadabra doesn't have the time to work on it anymore.

**Pull request closed without merging**
